#!/bin/bash
for i in {0..32} 
do
 if [ "$i" -eq 0 ] || [ "$i" -eq 10 ] || [ "$i" -eq 15 ] || [ "$i" -eq 21 ] ; then
      important='ref' 
 else
      important=''     
 fi
 out=`grep "outer SCF loop FAILED to converge after" ${i}out -c` 
# out1=`grep "ENERGY| Total FORCE_EVAL ( QS ) energy (a.u.):" ${i}out -c`
# out1=`grep "*** MAXIMUM NUMBER OF OPTIMIZATION STEPS REACHED ***" ${i}out -c`
 out1=`grep "SCF run converged in" ${i}out -c`
 out2=`grep "outer SCF loop converged in" ${i}out -c`
# out3=$((out+out2))
# echo ${i} $out $out1 $out2 $out3 $important
 echo ${i} $out $out1 $out2 $important
done

